# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='num_eyes',
            field=models.IntegerField(default=0),
        ),
    ]
