# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_num_eyes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'')),
                ('num_eyes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=b'documents/'),
        ),
    ]
