# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170606_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default=b'me.txt', max_length=100),
        ),
    ]
