# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170606_0305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneEyeDoc',
        ),
        migrations.DeleteModel(
            name='TwoEyeDoc',
        ),
        migrations.DeleteModel(
            name='ZeroEyeDoc',
        ),
    ]
